name: test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: list files
        run: |
          ls -l && pwd 
          echo $GITHUB_WORKSPACE

      -   name: Setup SSH Keys and known_hosts
          run: |
                 mkdir -p ~/.ssh/
                 echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                 sudo chmod 600 ~/.ssh/id_rsa
                 ssh-keyscan -p 1022 -H '54.236.25.192' >> ~/.ssh/known_hosts
                 ssh ubuntu@54.236.25.192 -p 1022  "hostname && ifconfig"
